<?php
/**
 * Pure-PHP Keccak-256 (the original Keccak padding used by Ethereum — NOT NIST SHA3-256).
 *
 * Requires 64-bit PHP (lanes are native 64-bit integers). Test vectors:
 *   Keccak::hash( '' )    = c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470
 *   Keccak::hash( 'abc' ) = 4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45
 *
 * @package ReserveChain
 */

namespace RC;

defined( 'ABSPATH' ) || exit;

final class Keccak {

	private const RATE = 136; // 1088-bit rate for Keccak-256.

	/** Rotation offsets r[x + 5y]. */
	private const ROT = array( 0, 1, 62, 28, 27, 36, 44, 6, 55, 20, 3, 10, 43, 25, 39, 41, 45, 15, 21, 8, 18, 2, 61, 56, 14 );

	private static ?array $rc = null;

	/**
	 * Keccak-256 digest.
	 *
	 * @param string $data Binary input.
	 * @param bool   $raw  True for 32 raw bytes, false for 64 lower-case hex characters.
	 */
	public static function hash( string $data, bool $raw = false ): string {
		if ( PHP_INT_SIZE < 8 ) {
			throw new \RuntimeException( 'Keccak requires 64-bit PHP.' );
		}
		$rc = self::round_constants();

		// Multi-rate padding (pad10*1) with the Keccak domain byte 0x01.
		$pad = self::RATE - ( strlen( $data ) % self::RATE );
		if ( 1 === $pad ) {
			$data .= "\x81";
		} else {
			$data .= "\x01" . str_repeat( "\x00", $pad - 2 ) . "\x80";
		}

		$s = array_fill( 0, 25, 0 );
		foreach ( str_split( $data, self::RATE ) as $block ) {
			$lanes = array_values( unpack( 'P17', $block ) );
			for ( $i = 0; $i < 17; $i++ ) {
				$s[ $i ] ^= $lanes[ $i ];
			}
			$s = self::permute( $s, $rc );
		}

		$out = pack( 'P4', $s[0], $s[1], $s[2], $s[3] );
		return $raw ? $out : bin2hex( $out );
	}

	private static function rotl( int $x, int $n ): int {
		if ( 0 === $n ) {
			return $x;
		}
		return ( $x << $n ) | ( ( $x >> ( 64 - $n ) ) & ( ( 1 << $n ) - 1 ) );
	}

	/** Round constants generated by the LFSR of the Keccak reference (avoids unsigned-literal issues). */
	private static function round_constants(): array {
		if ( null !== self::$rc ) {
			return self::$rc;
		}
		$r   = 1;
		$out = array();
		for ( $round = 0; $round < 24; $round++ ) {
			$c = 0;
			for ( $j = 0; $j < 7; $j++ ) {
				if ( $r & 1 ) {
					$c ^= 1 << ( ( 1 << $j ) - 1 );
				}
				$r = ( $r & 0x80 ) ? ( ( $r << 1 ) ^ 0x71 ) & 0xff : ( $r << 1 ) & 0xff;
			}
			$out[] = $c;
		}
		self::$rc = $out;
		return $out;
	}

	private static function permute( array $s, array $rc ): array {
		$c = array( 0, 0, 0, 0, 0 );
		$b = array_fill( 0, 25, 0 );
		for ( $round = 0; $round < 24; $round++ ) {
			// θ.
			for ( $x = 0; $x < 5; $x++ ) {
				$c[ $x ] = $s[ $x ] ^ $s[ $x + 5 ] ^ $s[ $x + 10 ] ^ $s[ $x + 15 ] ^ $s[ $x + 20 ];
			}
			for ( $x = 0; $x < 5; $x++ ) {
				$d = $c[ ( $x + 4 ) % 5 ] ^ self::rotl( $c[ ( $x + 1 ) % 5 ], 1 );
				for ( $y = 0; $y < 25; $y += 5 ) {
					$s[ $y + $x ] ^= $d;
				}
			}
			// ρ and π.
			for ( $x = 0; $x < 5; $x++ ) {
				for ( $y = 0; $y < 5; $y++ ) {
					$b[ $y + 5 * ( ( 2 * $x + 3 * $y ) % 5 ) ] = self::rotl( $s[ $x + 5 * $y ], self::ROT[ $x + 5 * $y ] );
				}
			}
			// χ.
			for ( $y = 0; $y < 25; $y += 5 ) {
				for ( $x = 0; $x < 5; $x++ ) {
					$s[ $y + $x ] = $b[ $y + $x ] ^ ( ( ~$b[ $y + ( $x + 1 ) % 5 ] ) & $b[ $y + ( $x + 2 ) % 5 ] );
				}
			}
			// ι.
			$s[0] ^= $rc[ $round ];
		}
		return $s;
	}
}
